@startuml Oppgave_1
left to right direction
:Main-Admin: as Admin
:Bruker: as Bruker 

Admin --> (Administrere brukerprofiler)
Admin --> (Administrere abonnement)
Admin --> (Håndtere tilbakemeldinger og klager)
Admin --> (Administrere systeminnstillinger)
Admin --> (Legge til og redigere innhold)


Bruker --> (Se anbefalt innhold)
Bruker --> (søke etter medieinnhold)
Bruker --> (Opprette og administrere brukerprofil)
(Opprette og administrere brukerprofil) --> (Abonnere og administrere abonnement)
Bruker --> (Vurdere og gi tilbakemelding på innhold)
Bruker --> (Velge og spille av medieinnhold)




@enduml